import { randomBytes } from 'crypto'
import {
  getActionsArtifactProvenanceWebHost,
  IActionsArtifactProvenanceCredentialRegistration,
} from '../lib/actions-artifact-provenance'
import { IActionsArtifactDownloadSender } from './actions-artifact-download-registry'

/** A lease is deliberately short because it authorizes one local verifier run. */
export const ActionsArtifactProvenanceCredentialLeaseLifetimeMilliseconds =
  5 * 60 * 1000
export const ActionsArtifactProvenanceCredentialLeaseMaximumPerSender = 4
export const ActionsArtifactProvenanceCredentialLeaseMaximumGlobal = 32

const handlePattern = /^[a-f0-9]{32}$/
const accountIdPattern = /^[1-9][0-9]{0,15}$/
const controlCharacterPattern = /[\u0000-\u001f\u007f-\u009f]/

/** Main-only claim retained while one verifier operation owns a lease. */
export interface IActionsArtifactProvenanceCredentialLease {
  readonly accountKey: string
  readonly endpoint: string
  readonly login: string
  readonly accountsGeneration: number
  readonly webHost: string
  readonly signal: AbortSignal
  isLive(): boolean
}

interface ILeaseEntry extends IActionsArtifactProvenanceCredentialRegistration {
  readonly handle: string
  readonly senderId: number
  readonly webHost: string
  readonly expiresAt: number
  readonly timer: ReturnType<typeof setTimeout>
  state: 'available' | 'claimed'
  operationId: string | null
  controller: AbortController | null
}

interface ISenderLeases {
  readonly sender: IActionsArtifactDownloadSender
  readonly handles: Set<string>
  readonly release: () => void
  accountsGeneration: number | null
}

type LeaseRevocationListener = (senderId: number, operationId: string) => void

export interface IActionsArtifactProvenanceCredentialLeaseRegistryDependencies {
  readonly now?: () => number
  readonly random?: (size: number) => Buffer
  readonly schedule?: (
    callback: () => void,
    delay: number
  ) => ReturnType<typeof setTimeout>
  readonly cancelSchedule?: (timer: ReturnType<typeof setTimeout>) => void
}

function record(value: unknown): Record<string, unknown> {
  if (
    typeof value !== 'object' ||
    value === null ||
    Array.isArray(value) ||
    (Object.getPrototypeOf(value) !== Object.prototype &&
      Object.getPrototypeOf(value) !== null)
  ) {
    throw new Error('The selected account registration is invalid.')
  }
  return value as Record<string, unknown>
}

function hasExactKeys(
  value: Record<string, unknown>,
  keys: ReadonlyArray<string>
): boolean {
  const actual = Object.keys(value).sort()
  const expected = [...keys].sort()
  return (
    actual.length === expected.length &&
    actual.every((key, index) => key === expected[index])
  )
}

function normalizeGeneration(value: unknown): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw new Error('The selected account generation is invalid.')
  }
  return value as number
}

function normalizeLogin(value: unknown): string {
  if (
    typeof value !== 'string' ||
    value.length === 0 ||
    value.length > 256 ||
    controlCharacterPattern.test(value)
  ) {
    throw new Error('The selected account login is invalid.')
  }
  return value
}

function normalizeGHEEndpoint(value: unknown): {
  readonly endpoint: string
  readonly webHost: string
} {
  if (typeof value !== 'string' || value.length === 0 || value.length > 2048) {
    throw new Error('The selected account endpoint is invalid.')
  }

  let webHost: string
  try {
    webHost = getActionsArtifactProvenanceWebHost(value)
  } catch {
    throw new Error('The selected account endpoint is unsupported.')
  }
  if (webHost === 'github.com') {
    throw new Error('The selected account endpoint is unsupported.')
  }

  // AccountsStore normalizes every current GHE.com account through
  // getEnterpriseAPIURL() to this exact API endpoint. Do not accept an
  // alternate web endpoint, path, userinfo, or noncanonical spelling here.
  const endpoint = `https://api.${webHost}/`
  if (value !== endpoint) {
    throw new Error('The selected account endpoint is invalid.')
  }
  return { endpoint, webHost }
}

/**
 * Account keys are generated by getAccountKey(account) as
 * `${account.endpoint}#${account.id}`. Reconstructing that exact string keeps
 * the renderer from pairing another account id with a credential endpoint.
 */
function normalizeAccountKey(value: unknown, endpoint: string): string {
  if (typeof value !== 'string' || value.length > 2100) {
    throw new Error('The selected account identity is invalid.')
  }
  const delimiter = value.lastIndexOf('#')
  if (delimiter <= 0 || delimiter === value.length - 1) {
    throw new Error('The selected account identity is invalid.')
  }
  const keyEndpoint = value.slice(0, delimiter)
  const rawId = value.slice(delimiter + 1)
  if (!accountIdPattern.test(rawId)) {
    throw new Error('The selected account identity is invalid.')
  }
  const id = Number(rawId)
  if (!Number.isSafeInteger(id) || `${id}` !== rawId) {
    throw new Error('The selected account identity is invalid.')
  }
  const accountKey = `${endpoint}#${id}`
  if (keyEndpoint !== endpoint || value !== accountKey) {
    throw new Error('The selected account identity is invalid.')
  }
  return accountKey
}

export function normalizeActionsArtifactProvenanceCredentialRegistration(
  value: unknown
): IActionsArtifactProvenanceCredentialRegistration {
  const registration = record(value)
  if (
    !hasExactKeys(registration, [
      'accountKey',
      'accountsGeneration',
      'endpoint',
      'login',
    ])
  ) {
    throw new Error('The selected account registration fields are invalid.')
  }
  const { endpoint } = normalizeGHEEndpoint(registration.endpoint)
  // Keep endpoint normalization before account-key validation to avoid
  // accepting a legacy keyring-key alias for a different endpoint spelling.
  return {
    accountKey: normalizeAccountKey(registration.accountKey, endpoint),
    endpoint,
    login: normalizeLogin(registration.login),
    accountsGeneration: normalizeGeneration(registration.accountsGeneration),
  }
}

/**
 * Holds opaque one-use account registrations without importing keytar. Token
 * lookup is intentionally delegated to a main-only adapter after archive and
 * bundle preparation has completed.
 */
export class ActionsArtifactProvenanceCredentialLeaseRegistry {
  private readonly now: () => number
  private readonly random: (size: number) => Buffer
  private readonly schedule: (
    callback: () => void,
    delay: number
  ) => ReturnType<typeof setTimeout>
  private readonly cancelSchedule: (
    timer: ReturnType<typeof setTimeout>
  ) => void
  private readonly entries = new Map<string, ILeaseEntry>()
  private readonly senders = new Map<number, ISenderLeases>()
  private readonly revocationListeners = new Set<LeaseRevocationListener>()

  public constructor(
    dependencies: IActionsArtifactProvenanceCredentialLeaseRegistryDependencies = {}
  ) {
    this.now = dependencies.now ?? Date.now
    this.random = dependencies.random ?? randomBytes
    this.schedule = dependencies.schedule ?? setTimeout
    this.cancelSchedule = dependencies.cancelSchedule ?? clearTimeout
  }

  /** Register a safe GHE.com identity and return a sender-bound opaque handle. */
  public register(
    sender: IActionsArtifactDownloadSender,
    value: unknown
  ): string | null {
    let registration: IActionsArtifactProvenanceCredentialRegistration
    try {
      registration =
        normalizeActionsArtifactProvenanceCredentialRegistration(value)
    } catch {
      return null
    }
    if (sender.isDestroyed()) {
      return null
    }
    this.expire()
    const owner = this.lifecycle(sender)
    if (
      owner.accountsGeneration !== null &&
      registration.accountsGeneration < owner.accountsGeneration
    ) {
      return null
    }

    const identityChanged = [...owner.handles].some(handle => {
      const current = this.entries.get(handle)
      return (
        current !== undefined &&
        (current.accountKey !== registration.accountKey ||
          current.endpoint !== registration.endpoint ||
          current.login !== registration.login)
      )
    })
    if (
      owner.accountsGeneration === null ||
      registration.accountsGeneration > owner.accountsGeneration ||
      identityChanged
    ) {
      this.revokeSenderLeases(owner, true)
    }
    owner.accountsGeneration = registration.accountsGeneration

    if (
      owner.handles.size >=
        ActionsArtifactProvenanceCredentialLeaseMaximumPerSender ||
      this.entries.size >= ActionsArtifactProvenanceCredentialLeaseMaximumGlobal
    ) {
      return null
    }
    const handle = this.newHandle()
    if (handle === null) {
      return null
    }

    let webHost: string
    try {
      webHost = getActionsArtifactProvenanceWebHost(registration.endpoint)
    } catch {
      return null
    }
    const now = this.now()
    if (!Number.isFinite(now)) {
      return null
    }
    const expiresAt =
      now + ActionsArtifactProvenanceCredentialLeaseLifetimeMilliseconds
    let timer: ReturnType<typeof setTimeout>
    try {
      timer = this.schedule(
        () => this.release(sender.id, handle),
        ActionsArtifactProvenanceCredentialLeaseLifetimeMilliseconds
      )
    } catch {
      return null
    }
    const entry: ILeaseEntry = {
      ...registration,
      handle,
      senderId: sender.id,
      webHost,
      expiresAt,
      timer,
      state: 'available',
      operationId: null,
      controller: null,
    }
    this.entries.set(handle, entry)
    owner.handles.add(handle)
    if (sender.isDestroyed()) {
      this.release(sender.id, handle)
      return null
    }
    return handle
  }

  /**
   * Atomically consume one handle before any verification await. The retained
   * claim remains internal so token rotation and revocation can be checked
   * after the verifier process tree has closed.
   */
  public claim(
    senderId: number,
    handle: unknown,
    operationId: string
  ): IActionsArtifactProvenanceCredentialLease | null {
    this.expire()
    if (!handlePattern.test(operationId) || typeof handle !== 'string') {
      return null
    }
    const entry = this.entries.get(handle)
    if (
      entry === undefined ||
      entry.senderId !== senderId ||
      entry.state !== 'available' ||
      entry.expiresAt <= this.now()
    ) {
      return null
    }
    const controller = new AbortController()
    entry.state = 'claimed'
    entry.operationId = operationId
    entry.controller = controller
    return {
      accountKey: entry.accountKey,
      endpoint: entry.endpoint,
      login: entry.login,
      accountsGeneration: entry.accountsGeneration,
      webHost: entry.webHost,
      signal: controller.signal,
      isLive: () =>
        this.entries.get(entry.handle) === entry &&
        entry.state === 'claimed' &&
        !controller.signal.aborted &&
        entry.expiresAt > this.now(),
    }
  }

  /** Explicit renderer release is idempotent and aborts only its active lease. */
  public release(senderId: number, handle: unknown): boolean {
    if (typeof handle !== 'string' || !handlePattern.test(handle)) {
      return false
    }
    const entry = this.entries.get(handle)
    if (entry === undefined || entry.senderId !== senderId) {
      return false
    }
    this.remove(entry, true)
    return true
  }

  /** Finish a claimed verifier run without turning a successful cleanup into a cancel. */
  public complete(senderId: number, handle: unknown): boolean {
    if (typeof handle !== 'string' || !handlePattern.test(handle)) {
      return false
    }
    const entry = this.entries.get(handle)
    if (entry === undefined || entry.senderId !== senderId) {
      return false
    }
    this.remove(entry, false)
    return true
  }

  /** Reject stale generations and abort only claims registered before the new one. */
  public invalidateGeneration(
    sender: IActionsArtifactDownloadSender,
    generation: unknown
  ): boolean {
    let normalized: number
    try {
      normalized = normalizeGeneration(generation)
    } catch {
      return false
    }
    if (sender.isDestroyed()) {
      return false
    }
    this.expire()
    const owner = this.lifecycle(sender)
    if (
      owner.accountsGeneration !== null &&
      normalized < owner.accountsGeneration
    ) {
      return false
    }
    if (
      owner.accountsGeneration === null ||
      normalized > owner.accountsGeneration
    ) {
      this.revokeSenderLeases(owner, true)
      owner.accountsGeneration = normalized
    }
    return true
  }

  /** Cancel the exact account-backed operation without touching another sender. */
  public cancelOperation(senderId: number, operationId: unknown): boolean {
    if (typeof operationId !== 'string' || !handlePattern.test(operationId)) {
      return false
    }
    for (const entry of this.entries.values()) {
      if (
        entry.senderId === senderId &&
        entry.state === 'claimed' &&
        entry.operationId === operationId
      ) {
        this.remove(entry, true)
        return true
      }
    }
    return false
  }

  public releaseAll(): void {
    for (const owner of [...this.senders.values()]) {
      this.revokeSenderLeases(owner, true)
      this.detach(owner)
    }
  }

  public onRevoked(listener: LeaseRevocationListener): () => void {
    this.revocationListeners.add(listener)
    return () => this.revocationListeners.delete(listener)
  }

  public get size(): number {
    this.expire()
    return this.entries.size
  }

  private lifecycle(sender: IActionsArtifactDownloadSender): ISenderLeases {
    const existing = this.senders.get(sender.id)
    if (existing !== undefined) {
      if (existing.sender === sender) {
        return existing
      }
      this.revokeSenderLeases(existing, true)
      this.detach(existing)
    }
    const release = () => this.releaseSender(sender.id)
    const created: ISenderLeases = {
      sender,
      handles: new Set<string>(),
      release,
      accountsGeneration: null,
    }
    this.senders.set(sender.id, created)
    sender.on('did-start-navigation', release)
    sender.once('destroyed', release)
    return created
  }

  private releaseSender(senderId: number): void {
    const owner = this.senders.get(senderId)
    if (owner === undefined) {
      return
    }
    this.revokeSenderLeases(owner, true)
    this.detach(owner)
  }

  private detach(owner: ISenderLeases): void {
    owner.sender.removeListener('did-start-navigation', owner.release)
    if (!owner.sender.isDestroyed()) {
      owner.sender.removeListener('destroyed', owner.release)
    }
    this.senders.delete(owner.sender.id)
  }

  private revokeSenderLeases(owner: ISenderLeases, notify: boolean): void {
    for (const handle of [...owner.handles]) {
      const entry = this.entries.get(handle)
      if (entry !== undefined) {
        this.remove(entry, notify)
      }
    }
  }

  private remove(entry: ILeaseEntry, notify: boolean): void {
    if (this.entries.get(entry.handle) !== entry) {
      return
    }
    this.entries.delete(entry.handle)
    this.cancelSchedule(entry.timer)
    this.senders.get(entry.senderId)?.handles.delete(entry.handle)
    if (notify && entry.state === 'claimed' && entry.controller !== null) {
      entry.controller.abort()
      if (entry.operationId !== null) {
        for (const listener of this.revocationListeners) {
          listener(entry.senderId, entry.operationId)
        }
      }
    }
  }

  private expire(): void {
    const now = this.now()
    for (const entry of [...this.entries.values()]) {
      if (entry.expiresAt <= now) {
        this.remove(entry, true)
      }
    }
  }

  private newHandle(): string | null {
    for (let attempt = 0; attempt < 32; attempt++) {
      let handle: string
      try {
        handle = this.random(16).toString('hex')
      } catch {
        return null
      }
      if (handlePattern.test(handle) && !this.entries.has(handle)) {
        return handle
      }
    }
    return null
  }
}

export const actionsArtifactProvenanceCredentialLeaseRegistry =
  new ActionsArtifactProvenanceCredentialLeaseRegistry()

export const registerActionsArtifactProvenanceCredentialLease = (
  sender: IActionsArtifactDownloadSender,
  value: unknown
) => actionsArtifactProvenanceCredentialLeaseRegistry.register(sender, value)

export const releaseActionsArtifactProvenanceCredentialLease = (
  senderId: number,
  handle: unknown
) => actionsArtifactProvenanceCredentialLeaseRegistry.release(senderId, handle)

export const invalidateActionsArtifactProvenanceCredentialLeaseGeneration = (
  sender: IActionsArtifactDownloadSender,
  generation: unknown
) =>
  actionsArtifactProvenanceCredentialLeaseRegistry.invalidateGeneration(
    sender,
    generation
  )

export const releaseAllActionsArtifactProvenanceCredentialLeases = () =>
  actionsArtifactProvenanceCredentialLeaseRegistry.releaseAll()
