/* generate-gitignore-catalog
 *
 * Utility script that reads a curated subset of the bundled github/gitignore
 * templates (app/static/common/gitignore/**) and emits a committed TypeScript
 * module (app/src/lib/gitignore/catalog.generated.ts) containing just the
 * template bodies keyed by id. Metadata (label/category/icon/markers/platform)
 * lives in the hand-authored catalog.ts alongside this generated file.
 *
 * Modeled on script/generate-octicons.ts: generate a TS module, commit the
 * output, import it normally. Run with:
 *   yarn generate-gitignore-catalog
 *
 * The github/gitignore collection is CC0-1.0; the generated file carries that
 * notice plus the exact upstream commit it was produced from.
 */

/* eslint-disable no-sync */

import * as fs from 'fs'
import * as Path from 'path'
import * as cp from 'child_process'

/**
 * Curated id -> source path (relative to the gitignore submodule root). Keep
 * this list in sync with the metadata table in
 * app/src/lib/gitignore/catalog.ts (a unit test enforces that every metadata
 * id resolves to a non-empty body here).
 */
const SOURCES: ReadonlyArray<readonly [string, string]> = [
  ['node', 'Node.gitignore'],
  ['python', 'Python.gitignore'],
  ['rust', 'Rust.gitignore'],
  ['go', 'Go.gitignore'],
  ['java', 'Java.gitignore'],
  ['visualstudio', 'VisualStudio.gitignore'],
  ['jetbrains', 'Global/JetBrains.gitignore'],
  ['vscode', 'Global/VisualStudioCode.gitignore'],
  ['macos', 'Global/macOS.gitignore'],
  ['windows', 'Global/Windows.gitignore'],
  ['linux', 'Global/Linux.gitignore'],
  ['unity', 'Unity.gitignore'],
  ['unrealengine', 'UnrealEngine.gitignore'],
  ['terraform', 'Terraform.gitignore'],
  ['jekyll', 'Jekyll.gitignore'],
  ['ruby', 'Ruby.gitignore'],
  ['composer', 'Composer.gitignore'],
  ['dart', 'Dart.gitignore'],
  ['flutter', 'Flutter.gitignore'],
]

const repoRoot = Path.dirname(__dirname)
const gitIgnoreRoot = Path.resolve(
  repoRoot,
  'app',
  'static',
  'common',
  'gitignore'
)
const outPath = Path.resolve(
  repoRoot,
  'app',
  'src',
  'lib',
  'gitignore',
  'catalog.generated.ts'
)

/** Resolve the exact upstream commit the bundled templates come from. */
function getSourceCommit(): string {
  // The templates are a git submodule pinned in the parent repo tree.
  try {
    const out = cp
      .execSync('git ls-tree HEAD -- app/static/common/gitignore', {
        cwd: repoRoot,
        encoding: 'utf8',
      })
      .trim()
    const match = out.match(/^\d+ commit ([0-9a-f]{40})\b/)
    if (match) {
      return match[1]
    }
  } catch {
    /* fall through */
  }

  try {
    return cp
      .execSync('git rev-parse HEAD', {
        cwd: gitIgnoreRoot,
        encoding: 'utf8',
      })
      .trim()
  } catch {
    return 'unknown'
  }
}

/** Normalize to LF and drop a trailing newline run. */
function normalizeBody(text: string): string {
  return text.replace(/\r\n?/g, '\n').replace(/\n+$/, '')
}

/** Escape a body for embedding inside a template literal. */
function escapeForTemplateLiteral(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
}

function main() {
  const sourceCommit = getSourceCommit()

  const bodies = SOURCES.map(([id, relPath]) => {
    const fullPath = Path.join(gitIgnoreRoot, relPath)
    const raw = fs.readFileSync(fullPath, 'utf8')
    const body = normalizeBody(raw)
    if (body.length === 0) {
      throw new Error(`Empty gitignore body for ${id} (${relPath})`)
    }
    return { id, relPath, body }
  })

  console.log(`Writing ${bodies.length} gitignore template bodies...`)

  const out = fs.createWriteStream(outPath, { encoding: 'utf-8' })

  out.write(`/*
 * This file is automatically generated by script/generate-gitignore-catalog.ts.
 * Manually changing this file will only lead to sadness.
 *
 * The template bodies below are taken verbatim from GitHub's collection of
 * .gitignore templates (https://github.com/github/gitignore), which is
 * published under CC0-1.0 (public domain dedication). No warranty is implied.
 *
 * Upstream source commit: ${sourceCommit}
 */

/* eslint-disable */

/** Raw .gitignore template bodies (LF-only) keyed by catalog template id. */
export const gitIgnoreTemplateBodies: { readonly [id: string]: string } = {
`)

  for (const { id, relPath, body } of bodies) {
    out.write(`  // ${relPath}\n`)
    out.write(
      `  ${JSON.stringify(id)}: \`${escapeForTemplateLiteral(body)}\`,\n`
    )
  }

  out.write(`}\n`)
  out.end()

  console.log('Ensuring generated file is formatted correctly...')
  const yarnExecutable = process.platform === 'win32' ? 'yarn.cmd' : 'yarn'
  cp.spawn(yarnExecutable, ['lint:fix'], {
    cwd: repoRoot,
    stdio: 'inherit',
    // Spawning a .cmd shim on Windows requires a shell.
    shell: process.platform === 'win32',
  })
}

main()
